import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/etc/profiles/per-user/adrian/bin/google-chrome-stable',args:['--no-sandbox']});
const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const base=process.env.APP_URL||'http://127.0.0.1:8766/';
await page.route('https://raw.githubusercontent.com/adichannnnnhere64/jakarta-ee-question-bank/main/catalog.json',route=>route.fulfill({path:'content/enterprise/catalog.json',contentType:'application/json'}));
try{
 await page.goto(base);await page.getByRole('heading',{name:'Small steps. Stronger skills.'}).waitFor();
 const examContext=await browser.newContext();
 try{
  const examPage=await examContext.newPage();
  await examPage.route('https://raw.githubusercontent.com/adichannnnnhere64/jakarta-ee-question-bank/main/catalog.json',route=>route.fulfill({path:'content/enterprise/catalog.json',contentType:'application/json'}));
  await examPage.goto(base);
  await examPage.getByRole('heading',{name:'Jakarta Competency Exam',exact:true}).waitFor();
  await examPage.getByLabel('Search questions and topics').fill('Solutioning, Deployment and Implementation Knowledge');
  await examPage.getByRole('heading',{name:'Question results'}).waitFor();
  assert.equal(await examPage.getByRole('button',{name:'Practice this question'}).count(),10);
  await examPage.getByLabel('Search questions and topics').fill('');
  await examPage.screenshot({path:'/tmp/tutorialz-jakarta-exam-library.png',fullPage:true});
  await examPage.getByRole('button',{name:'Start practicing'}).click();
  await examPage.locator('.desktop-test-picker').getByLabel('Jakarta Competency Exam').check();
  await examPage.getByLabel('Number of questions').fill('50');
  await examPage.getByRole('button',{name:'Start session'}).click();
  await examPage.getByRole('button',{name:'Check answer'}).waitFor();
  await examPage.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.questions.length===50);
  const examState=JSON.parse(await examPage.evaluate(()=>window.tutorialz.load('learner-state')));
  const examQuestions=examState.progress.active.questions;
  assert.equal(new Set(examQuestions.map(q=>q.topic)).size,10);
  assert.equal(new Set(examQuestions.map(q=>q.second_topic)).size,5);
  assert(examQuestions.every(q=>q.id.startsWith('jakarta-competency-')));
  await examPage.getByRole('radio').nth(examQuestions[0].correct[0]).check();
  await examPage.getByRole('button',{name:'Check answer'}).click();
  await examPage.getByText("That's correct",{exact:false}).waitFor();
  await examPage.screenshot({path:'/tmp/tutorialz-jakarta-exam-question.png',fullPage:true});
  await examPage.setViewportSize({width:390,height:844});
  assert.equal(await examPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await examPage.screenshot({path:'/tmp/tutorialz-jakarta-exam-mobile.png',fullPage:true});
 }finally{await examContext.close();}
 const dummyContext=await browser.newContext();
 try{
  const dummyPage=await dummyContext.newPage();
  await dummyPage.route('https://raw.githubusercontent.com/adichannnnnhere64/jakarta-ee-question-bank/main/catalog.json',route=>route.fulfill({path:'content/enterprise/catalog.json',contentType:'application/json'}));
  await dummyPage.goto(base);
  await dummyPage.getByRole('heading',{name:'Jakarta Dummy Exam',exact:true}).waitFor();
  await dummyPage.getByLabel('Search questions and topics').fill('ActiveMQ Artemis');
  await dummyPage.getByRole('heading',{name:'Question results'}).waitFor();
  assert.equal(await dummyPage.getByRole('button',{name:'Practice this question'}).count(),40);
  await dummyPage.getByLabel('Search questions and topics').fill('');
  await dummyPage.getByRole('button',{name:'Start practicing'}).click();
  await dummyPage.locator('.desktop-test-picker').getByLabel('Jakarta Dummy Exam').check();
  await dummyPage.getByLabel('Number of questions').fill('200');
  await dummyPage.getByRole('button',{name:'Start session'}).click();
  await dummyPage.getByRole('button',{name:'Check answer'}).waitFor();
  await dummyPage.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.questions.length===200);
  const dummy=JSON.parse(await dummyPage.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active.questions;
  assert.equal(new Set(dummy.map(q=>q.topic)).size,6);
  assert(dummy.every(q=>q.id.startsWith('jakarta-dummy-')));
  await dummyPage.getByRole('radio').nth(dummy[0].correct[0]).check();
  await dummyPage.getByRole('button',{name:'Check answer'}).click();
  await dummyPage.getByText("That's correct",{exact:false}).waitFor();
  await dummyPage.screenshot({path:'/tmp/tutorialz-jakarta-dummy-exam.png',fullPage:true});
 }finally{await dummyContext.close();}
 await page.getByLabel('Search questions and topics').fill('optimistic locking');
 await page.getByRole('heading',{name:'Question results'}).waitFor();
 assert(await page.getByRole('button',{name:'Practice this question'}).count()>0);
 for(const topic of ['Type inference with var','Covariant return']){
  await page.getByLabel('Search questions and topics').fill(topic);
  await page.getByRole('heading',{name:'Question results'}).waitFor();
  assert(await page.getByRole('button',{name:'Practice this question'}).count()>0,`No result for ${topic}`);
 }
 await page.getByLabel('Search questions and topics').fill('');
 await page.screenshot({path:'/tmp/tutorialz-library.png',fullPage:true});
 await page.getByRole('button',{name:'Start practicing'}).click();
 await page.locator('.desktop-test-picker').getByLabel('Platform practice').first().check();
 await page.getByLabel('Number of questions').fill('2');await page.getByRole('button',{name:'Start session'}).click();
 await page.getByRole('button',{name:'Check answer'}).waitFor();
 await page.waitForFunction(async()=>{const s=await window.tutorialz.load('learner-state');return s&&JSON.parse(s).progress.active?.questions?.length===2;});
 const session=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 await page.getByRole('radio').nth(session.questions[0].correct[0]).check();
 await page.getByRole('button',{name:'Check answer'}).click();await page.getByText("That's correct",{exact:false}).waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Submitted answer should no longer be selected');
 assert.equal(await page.locator('.choice.selected').count(),0,'Submitted choice should lose its selected style');
 await page.getByRole('button',{name:'Next question'}).click();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Next question should start without a selection');
 assert.equal(await page.locator('.choice.selected').count(),0,'Next question should start without a selected style');
 await page.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.position===1);
 await page.reload();await page.getByRole('button',{name:'Session & results',exact:false}).click();await page.getByRole('button',{name:'Check answer'}).waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Next question should stay clear after reload');
 await page.getByRole('radio').nth(session.questions[1].correct[0]).check();
 await page.getByRole('button',{name:'Check answer'}).click();await page.getByRole('button',{name:'View results'}).click();await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 await page.getByRole('button',{name:'Finish session',exact:true}).click();
 await page.locator('.desktop-test-picker').getByLabel('Platform practice').first().check();
 await page.getByLabel('Number of questions').fill('2');await page.getByRole('checkbox',{name:/Fast mode/}).check();
 await page.getByRole('button',{name:'Start session'}).click();
 await page.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.fast_mode===true);
 const fastSession=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 await page.getByRole('radio').nth(fastSession.questions[0].correct[0]).check();
 await page.getByText('QUESTION 2 OF 2').waitFor();
 await page.waitForFunction(async()=>Object.keys(JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.drafts||{}).length>0);
 assert.equal(Object.keys(JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active.drafts).length,1,'One click should save only one answer');
 assert.equal(await page.locator('.choice.selected').count(),0,'Fast mode should clear the next question');
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Fast mode should clear the next radio input');
 await page.getByRole('button',{name:/Previous question/}).click();
 assert(await page.getByRole('radio').nth(fastSession.questions[0].correct[0]).isChecked(),'Previous question should restore its answer');
 await page.getByRole('radio').nth((fastSession.questions[0].correct[0]+1)%fastSession.questions[0].options.length).check();
 await page.getByText('QUESTION 2 OF 2').waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Returning forward should clear the next radio input');
 await page.getByRole('radio').nth(fastSession.questions[1].correct[0]).check();
 await page.getByRole('button',{name:'Finish exam'}).click();await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 const fastResults=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 assert.equal(fastResults.answers[fastSession.questions[0].id].correct,false);
 assert.equal(fastResults.answers[fastSession.questions[1].id].correct,true);
 const wrongReview=page.locator('.results-row').first();await wrongReview.locator('summary').click();
 const submittedIndex=fastResults.answers[fastSession.questions[0].id].answer.value[0];
 assert((await wrongReview.locator('.submitted-answer').innerText()).includes(fastSession.questions[0].options[submittedIndex]),'Fast-mode review must show the saved wrong choice');
 await page.getByRole('button',{name:'Practice',exact:false}).first().click();
 await page.getByRole('button',{name:'View results'}).click();
 await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 await page.getByRole('button',{name:'Finish session',exact:true}).click();
 await page.getByRole('button',{name:'Settings & backups',exact:false}).click();
 await page.getByRole('button',{name:'Sync questions now'}).click();
 await page.getByText('Questions are up to date.',{exact:false}).waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export progress',exact:true}).click();const download=await downloadPromise;const backup=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(backup.attempts.length,4);assert.equal(backup.attempts.filter(a=>a.correct).length,3);
 await page.getByLabel('Java pack directory URL').fill(base+'java-pack/');await page.getByRole('button',{name:'Download / verify pack'}).click();await page.getByText('Java pack installed. Code practice is ready offline.').waitFor();
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Small steps. Stronger skills.'}).waitFor();
 const sample=JSON.parse(await fs.readFile('content/samples.json','utf8'));
 const javaQuestion=sample[0].tests[0].questions.find(q=>q.type==='java');
 const javaResult=await page.evaluate(async q=>window.tutorialz.java({question:q,source:q.reference}),javaQuestion);assert(javaResult.passed);await context.setOffline(false);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/tutorialz-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.goto(base);await page.getByRole('button',{name:/Open Java Enterprise and Jakarta EE/}).first().waitFor();
 const mobileNav=page.getByRole('navigation',{name:'Learner navigation'});assert(await mobileNav.isVisible());
 await page.getByRole('button',{name:/Open Java Enterprise and Jakarta EE/}).first().click();await page.locator('.mobile-test-row').first().click();
 assert.equal(await page.locator('.mobile-test-picker input:checked').count(),1,'Course test should be selected in mobile practice');
 await page.getByRole('button',{name:'Start session'}).click();await page.getByRole('button',{name:'Check answer'}).waitFor();
 assert.equal(await mobileNav.isVisible(),false,'Session should use focused navigation');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.goto(base+'author/');await page.getByRole('heading',{name:'Good questions start here.'}).waitFor();await page.getByRole('button',{name:'Tests',exact:true}).click();await page.getByRole('button',{name:'1. Which type stores a true/false value?',exact:true}).click();await page.getByRole('button',{name:'Preview question',exact:true}).click();
 await page.getByRole('button',{name:'Check preview answer'}).waitFor();
 await page.screenshot({path:'/tmp/tutorialz-author.png',fullPage:true});
 console.log('PASS: learner grading, fast mode navigation and revision, reload/resume, results, progress export, offline shell + Java, mobile layout, authoring preview');
 assert.deepEqual(errors,[]);
}finally{await browser.close();}
