import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/etc/profiles/per-user/adrian/bin/google-chrome-stable',args:['--no-sandbox']});
const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const base=process.env.APP_URL||'http://127.0.0.1:8766/';
await page.route('https://raw.githubusercontent.com/adichannnnnhere64/jakarta-ee-question-bank/main/catalog.json',route=>route.fulfill({path:'content/enterprise/catalog.json',contentType:'application/json'}));
try{
 await page.goto(base);await page.getByRole('heading',{name:'Small steps. Stronger skills.'}).waitFor();
 await page.getByLabel('Search questions and topics').fill('optimistic locking');
 await page.getByRole('heading',{name:'Question results'}).waitFor();
 assert(await page.getByRole('button',{name:'Practice this question'}).count()>0);
 for(const topic of ['Type inference with var','Covariant return']){
  await page.getByLabel('Search questions and topics').fill(topic);
  await page.getByRole('heading',{name:'Question results'}).waitFor();
  assert(await page.getByRole('button',{name:'Practice this question'}).count()>0,`No result for ${topic}`);
 }
 await page.getByLabel('Search questions and topics').fill('');
 await page.screenshot({path:'/tmp/tutorialz-library.png',fullPage:true});
 await page.getByRole('button',{name:'Start practicing'}).click();
 await page.getByLabel('Platform practice').first().check();
 await page.getByLabel('Number of questions').fill('2');await page.getByRole('button',{name:'Start session'}).click();
 await page.getByRole('button',{name:'Check answer'}).waitFor();
 await page.waitForFunction(async()=>{const s=await window.tutorialz.load('learner-state');return s&&JSON.parse(s).progress.active?.questions?.length===2;});
 const session=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 await page.getByRole('radio').nth(session.questions[0].correct[0]).check();
 await page.getByRole('button',{name:'Check answer'}).click();await page.getByText("That's correct",{exact:false}).waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Submitted answer should no longer be selected');
 assert.equal(await page.locator('.choice.selected').count(),0,'Submitted choice should lose its selected style');
 await page.getByRole('button',{name:'Next question'}).click();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Next question should start without a selection');
 assert.equal(await page.locator('.choice.selected').count(),0,'Next question should start without a selected style');
 await page.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.position===1);
 await page.reload();await page.getByRole('button',{name:'Session & results',exact:false}).click();await page.getByRole('button',{name:'Check answer'}).waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Next question should stay clear after reload');
 await page.getByRole('radio').nth(session.questions[1].correct[0]).check();
 await page.getByRole('button',{name:'Check answer'}).click();await page.getByRole('button',{name:'View results'}).click();await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 await page.getByRole('button',{name:'Finish session',exact:true}).click();
 await page.getByLabel('Platform practice').first().check();
 await page.getByLabel('Number of questions').fill('2');await page.getByRole('checkbox',{name:/Fast mode/}).check();
 await page.getByRole('button',{name:'Start session'}).click();
 await page.waitForFunction(async()=>JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.fast_mode===true);
 const fastSession=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 await page.getByRole('radio').nth(fastSession.questions[0].correct[0]).check();
 await page.getByText('QUESTION 2 OF 2').waitFor();
 await page.waitForFunction(async()=>Object.keys(JSON.parse(await window.tutorialz.load('learner-state')).progress.active?.drafts||{}).length>0);
 assert.equal(Object.keys(JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active.drafts).length,1,'One click should save only one answer');
 assert.equal(await page.locator('.choice.selected').count(),0,'Fast mode should clear the next question');
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Fast mode should clear the next radio input');
 await page.getByRole('button',{name:/Previous question/}).click();
 assert(await page.getByRole('radio').nth(fastSession.questions[0].correct[0]).isChecked(),'Previous question should restore its answer');
 await page.getByRole('radio').nth((fastSession.questions[0].correct[0]+1)%fastSession.questions[0].options.length).check();
 await page.getByText('QUESTION 2 OF 2').waitFor();
 assert.equal(await page.getByRole('radio',{checked:true}).count(),0,'Returning forward should clear the next radio input');
 await page.getByRole('radio').nth(fastSession.questions[1].correct[0]).check();
 await page.getByRole('button',{name:'Finish exam'}).click();await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 const fastResults=JSON.parse(await page.evaluate(()=>window.tutorialz.load('learner-state'))).progress.active;
 assert.equal(fastResults.answers[fastSession.questions[0].id].correct,false);
 assert.equal(fastResults.answers[fastSession.questions[1].id].correct,true);
 await page.getByRole('button',{name:'Practice',exact:false}).first().click();
 await page.getByRole('button',{name:'View results'}).click();
 await page.getByRole('heading',{name:'Every attempt counts.'}).waitFor();
 await page.getByRole('button',{name:'Finish session',exact:true}).click();
 await page.getByRole('button',{name:'Settings & backups',exact:false}).click();
 await page.getByRole('button',{name:'Sync questions now'}).click();
 await page.getByText('Questions are up to date.',{exact:false}).waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export progress',exact:true}).click();const download=await downloadPromise;const backup=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(backup.attempts.length,4);assert.equal(backup.attempts.filter(a=>a.correct).length,3);
 await page.getByLabel('Java pack directory URL').fill(base+'java-pack/');await page.getByRole('button',{name:'Download / verify pack'}).click();await page.getByText('Java pack installed. Code practice is ready offline.').waitFor();
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Small steps. Stronger skills.'}).waitFor();
 const sample=JSON.parse(await fs.readFile('content/samples.json','utf8'));
 const javaQuestion=sample[0].tests[0].questions.find(q=>q.type==='java');
 const javaResult=await page.evaluate(async q=>window.tutorialz.java({question:q,source:q.reference}),javaQuestion);assert(javaResult.passed);await context.setOffline(false);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/tutorialz-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.goto(base+'author/');await page.getByRole('heading',{name:'Good questions start here.'}).waitFor();await page.getByRole('button',{name:'Tests',exact:true}).click();await page.getByRole('button',{name:'1. Which type stores a true/false value?',exact:true}).click();await page.getByRole('button',{name:'Preview question',exact:true}).click();
 await page.getByRole('button',{name:'Check preview answer'}).waitFor();
 await page.screenshot({path:'/tmp/tutorialz-author.png',fullPage:true});
 console.log('PASS: learner grading, fast mode navigation and revision, reload/resume, results, progress export, offline shell + Java, mobile layout, authoring preview');
 assert.deepEqual(errors,[]);
}finally{await browser.close();}
